export const FETCH_DATA_PRODUCTS = 'FETCH_DATA_PRODUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_QUANTITY_TO_CART = 'UPDATE_QUANTITY_TO_CART'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'